/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menus;

import control.View.Tela;

/**
 *
 * @author Aline
 */
public class FuncionarioMenuView extends javax.swing.JPanel {

    /**
     * Creates new form FuncionarioMenuView
     */
    public FuncionarioMenuView(String permissao) {
        initComponents();
        
        if(permissao.equals("Porteiro") || permissao.equals("Morador") || permissao.equals("MoradorMestre")){
            this.cadastrarFuncionariojButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFuncionariojButton = new javax.swing.JButton();
        consultarFuncionariojButton = new javax.swing.JButton();

        cadastrarFuncionariojButton.setText("Cadastrar Funcionário");
        cadastrarFuncionariojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionariojButtonActionPerformed(evt);
            }
        });

        consultarFuncionariojButton.setText("Consultar Funcionário");
        consultarFuncionariojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFuncionariojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(cadastrarFuncionariojButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarFuncionariojButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarFuncionariojButton)
                    .addComponent(consultarFuncionariojButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncionariojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionariojButtonActionPerformed
         Tela.atualizaTela("CadastroFuncionario");

    }//GEN-LAST:event_cadastrarFuncionariojButtonActionPerformed

    private void consultarFuncionariojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFuncionariojButtonActionPerformed
        Tela.atualizaTela("ConsultarFuncionarios");
    }//GEN-LAST:event_consultarFuncionariojButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarFuncionariojButton;
    private javax.swing.JButton consultarFuncionariojButton;
    // End of variables declaration//GEN-END:variables
}
