/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menus;

import control.View.Tela;

/**
 *
 * @author Aline
 */
public class ReclamacoesMenuView extends javax.swing.JPanel {

    /**
     * Creates new form reclamacoesMenuView
     */
    public ReclamacoesMenuView(String permissao) {
        initComponents();
        
        if(permissao.equals("Porteiro")){
            this.RegistrarReclamacoesjButton.setVisible(false);
        }
        if(permissao.equals("Porteiro") || permissao.equals("Morador") || permissao.equals("MoradorMestre")){
            this.ResponderReclamacoesjButton.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarReclamacoesjButton = new javax.swing.JButton();
        VisualizarReclamacoesjButton = new javax.swing.JButton();
        ResponderReclamacoesjButton = new javax.swing.JButton();

        RegistrarReclamacoesjButton.setText("Registar Reclamações");
        RegistrarReclamacoesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarReclamacoesjButtonActionPerformed(evt);
            }
        });

        VisualizarReclamacoesjButton.setText("Visualizar Reclamações");
        VisualizarReclamacoesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarReclamacoesjButtonActionPerformed(evt);
            }
        });

        ResponderReclamacoesjButton.setText("Responder Reclamações");
        ResponderReclamacoesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponderReclamacoesjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResponderReclamacoesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrarReclamacoesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisualizarReclamacoesjButton)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarReclamacoesjButton)
                    .addComponent(VisualizarReclamacoesjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(ResponderReclamacoesjButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarReclamacoesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarReclamacoesjButtonActionPerformed
        Tela.atualizaTela("RegistrarReclamacao");
    }//GEN-LAST:event_RegistrarReclamacoesjButtonActionPerformed

    private void VisualizarReclamacoesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarReclamacoesjButtonActionPerformed
        Tela.atualizaTela("VisualizarReclamacao");
    }//GEN-LAST:event_VisualizarReclamacoesjButtonActionPerformed

    private void ResponderReclamacoesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponderReclamacoesjButtonActionPerformed
        Tela.atualizaTela("ResponderReclamacao");

    }//GEN-LAST:event_ResponderReclamacoesjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarReclamacoesjButton;
    private javax.swing.JButton ResponderReclamacoesjButton;
    private javax.swing.JButton VisualizarReclamacoesjButton;
    // End of variables declaration//GEN-END:variables
}
