/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author aline.lima
 */
public class TesteMenu extends javax.swing.JPanel {

    /**
     * Creates new form TesteMenu
     */
    public TesteMenu( String t) {
        initComponents();
        if(t=="Porteiro"){
            this.financeiroMenuButton.setVisible(false);
            this.moradoresMenuButton.setVisible(false);
            this.reservasMenuButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moradoresMenuButton = new javax.swing.JButton();
        financeiroMenuButton = new javax.swing.JButton();
        portariaMenuButton = new javax.swing.JButton();
        reservasMenuButton = new javax.swing.JButton();
        infoPessoaisMenuButton = new javax.swing.JButton();
        LogoutMenuButton = new javax.swing.JButton();

        moradoresMenuButton.setText("Moradores");

        financeiroMenuButton.setText("Financeiro");

        portariaMenuButton.setText("Entrada/Saida");
        portariaMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portariaMenuButtonActionPerformed(evt);
            }
        });

        reservasMenuButton.setText("Reservas");

        infoPessoaisMenuButton.setText("Inf. Pessoais");

        LogoutMenuButton.setText("Logout");
        LogoutMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(portariaMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financeiroMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moradoresMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservasMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPessoaisMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moradoresMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(financeiroMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(portariaMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservasMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoPessoaisMenuButton)
                .addGap(18, 18, 18)
                .addComponent(LogoutMenuButton)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMenuButtonActionPerformed

    private void portariaMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portariaMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portariaMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutMenuButton;
    private javax.swing.JButton financeiroMenuButton;
    private javax.swing.JButton infoPessoaisMenuButton;
    private javax.swing.JButton moradoresMenuButton;
    private javax.swing.JButton portariaMenuButton;
    private javax.swing.JButton reservasMenuButton;
    // End of variables declaration//GEN-END:variables
}
