/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

/**
 *
 * @author Aline
 */
public class CadastroEncomendasView extends javax.swing.JPanel {

    /**
     * Creates new form CadastroEncomendasView
     */
    public CadastroEncomendasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DestinatariojLabel = new javax.swing.JLabel();
        EnderecojLabel = new javax.swing.JLabel();
        RecebimentojLabel = new javax.swing.JLabel();
        EntregajLabel = new javax.swing.JLabel();
        DestinatariojTextField = new javax.swing.JTextField();
        EnderecojTextField = new javax.swing.JTextField();
        RecebimentojFormattedTextField = new javax.swing.JFormattedTextField();
        EntregajFormattedTextField = new javax.swing.JFormattedTextField();
        CodigoCorrespondenciajTextField = new javax.swing.JTextField();
        CodigoCorrespondenciajLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        DestinatariojLabel.setText("Destinatário:");

        EnderecojLabel.setText("Endereço:");

        RecebimentojLabel.setText("Recebimento:");

        EntregajLabel.setText("Entrega:");

        DestinatariojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinatariojTextFieldActionPerformed(evt);
            }
        });

        EnderecojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecojTextFieldActionPerformed(evt);
            }
        });

        CodigoCorrespondenciajTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoCorrespondenciajTextFieldActionPerformed(evt);
            }
        });

        CodigoCorrespondenciajLabel.setText("Código correspondência:");

        jButton1.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(EnderecojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnderecojTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(RecebimentojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecebimentojFormattedTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntregajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntregajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DestinatariojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestinatariojTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodigoCorrespondenciajLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodigoCorrespondenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestinatariojLabel)
                    .addComponent(DestinatariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecojLabel)
                    .addComponent(EnderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCorrespondenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoCorrespondenciajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecebimentojLabel)
                    .addComponent(EntregajLabel)
                    .addComponent(RecebimentojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntregajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DestinatariojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinatariojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinatariojTextFieldActionPerformed

    private void EnderecojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecojTextFieldActionPerformed

    private void CodigoCorrespondenciajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoCorrespondenciajTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoCorrespondenciajTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoCorrespondenciajLabel;
    private javax.swing.JTextField CodigoCorrespondenciajTextField;
    private javax.swing.JLabel DestinatariojLabel;
    private javax.swing.JTextField DestinatariojTextField;
    private javax.swing.JLabel EnderecojLabel;
    private javax.swing.JTextField EnderecojTextField;
    private javax.swing.JFormattedTextField EntregajFormattedTextField;
    private javax.swing.JLabel EntregajLabel;
    private javax.swing.JFormattedTextField RecebimentojFormattedTextField;
    private javax.swing.JLabel RecebimentojLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
