/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

import control.domain.VisitanteControl;
import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;

/**
 *
 * @author Aline
 */
public class CadastroVisitanteView extends javax.swing.JPanel {

    /**
     * Creates new form CadastroVisitanteView
     */
    public CadastroVisitanteView() {
        initComponents();
        
        visitanteControl = VisitanteControl.getVisitanteControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomejLabel = new javax.swing.JLabel();
        CPFjLabel = new javax.swing.JLabel();
        NomejTextField = new javax.swing.JTextField();
        CPFjTextField = new javax.swing.JTextField();
        PrestadorServicojCheckBox = new javax.swing.JCheckBox();
        TelefonejLabel = new javax.swing.JLabel();
        TelefonejTextField = new javax.swing.JTextField();
        EntradajButton = new javax.swing.JButton();
        SaidajButton = new javax.swing.JButton();
        MoradorjLabel = new javax.swing.JLabel();
        NomeMoradorjLabel = new javax.swing.JLabel();
        EnderecojLabel = new javax.swing.JLabel();
        NomeMoradorjTextField = new javax.swing.JTextField();
        EnderecojTextField = new javax.swing.JTextField();
        VisitantejLabel = new javax.swing.JLabel();

        NomejLabel.setText("Nome:");

        CPFjLabel.setText("CPF:");

        PrestadorServicojCheckBox.setText("Prestador de Serviços");
        PrestadorServicojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestadorServicojCheckBoxActionPerformed(evt);
            }
        });

        TelefonejLabel.setText("Telefone:");

        EntradajButton.setText("Registrar Entrada");
        EntradajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradajButtonActionPerformed(evt);
            }
        });

        SaidajButton.setText("Registrar Saída");
        SaidajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidajButtonActionPerformed(evt);
            }
        });

        MoradorjLabel.setText("Morador Responsável:");

        NomeMoradorjLabel.setText("Nome:");

        EnderecojLabel.setText("Endereço:");

        VisitantejLabel.setText("Visitante:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomejTextField))
                    .addComponent(PrestadorServicojCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CPFjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CPFjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TelefonejLabel)
                        .addGap(10, 10, 10)
                        .addComponent(TelefonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntradajButton)
                        .addGap(18, 18, 18)
                        .addComponent(SaidajButton))
                    .addComponent(MoradorjLabel)
                    .addComponent(VisitantejLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeMoradorjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeMoradorjTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnderecojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnderecojTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(VisitantejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomejLabel)
                    .addComponent(NomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFjLabel)
                    .addComponent(CPFjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonejLabel)
                    .addComponent(TelefonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PrestadorServicojCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntradajButton)
                    .addComponent(SaidajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoradorjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeMoradorjLabel)
                    .addComponent(NomeMoradorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecojLabel)
                    .addComponent(EnderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrestadorServicojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestadorServicojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrestadorServicojCheckBoxActionPerformed

    private void EntradajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradajButtonActionPerformed
        Date date;
        date= Date.valueOf(LocalDate.now());
        
        visitanteControl.salvarVisitante(this.NomeMoradorjTextField.getText(), this.CPFjTextField.getText(),
                this.TelefonejTextField.getText(), this.PrestadorServicojCheckBox.isSelected(),date ,null);
    }//GEN-LAST:event_EntradajButtonActionPerformed

    private void SaidajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidajButtonActionPerformed
        Date date;
        date= Date.valueOf(LocalDate.now());
        
        visitanteControl.salvarVisitante(this.NomeMoradorjTextField.getText(), this.CPFjTextField.getText(),
                this.TelefonejTextField.getText(), this.PrestadorServicojCheckBox.isSelected(),null ,date);
    }//GEN-LAST:event_SaidajButtonActionPerformed

VisitanteControl visitanteControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFjLabel;
    private javax.swing.JTextField CPFjTextField;
    private javax.swing.JLabel EnderecojLabel;
    private javax.swing.JTextField EnderecojTextField;
    private javax.swing.JButton EntradajButton;
    private javax.swing.JLabel MoradorjLabel;
    private javax.swing.JLabel NomeMoradorjLabel;
    private javax.swing.JTextField NomeMoradorjTextField;
    private javax.swing.JLabel NomejLabel;
    private javax.swing.JTextField NomejTextField;
    private javax.swing.JCheckBox PrestadorServicojCheckBox;
    private javax.swing.JButton SaidajButton;
    private javax.swing.JLabel TelefonejLabel;
    private javax.swing.JTextField TelefonejTextField;
    private javax.swing.JLabel VisitantejLabel;
    // End of variables declaration//GEN-END:variables
}
