/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paineis;

/**
 *
 * @author Aline
 */
public class IncluirFinanceiroView extends javax.swing.JPanel {

    /**
     * Creates new form IncluirLancamentoView
     */
    public IncluirFinanceiroView() {
        initComponents();
        
        RecDesjComboBox.removeAllItems();
        RecDesjComboBox.addItem("Receita");
        RecDesjComboBox.addItem("Despesa");
       
        TipoPgtojComboBox.removeAllItems();
        TipoPgtojComboBox.addItem("Boleto");
        TipoPgtojComboBox.addItem("Cheque");
        TipoPgtojComboBox.addItem("Depósito em Conta");
        TipoPgtojComboBox.addItem("Dinheiro");
        TipoPgtojComboBox.addItem("Outro");
        
        TipoLancjComboBox.removeAllItems();
        TipoLancjComboBox.addItem("Multas");
        TipoLancjComboBox.addItem("Taxa de condomínio");
        TipoLancjComboBox.addItem("Taxa de locação de área");
        TipoLancjComboBox.addItem("Pagamento à fornecedor");
        TipoLancjComboBox.addItem("Outro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FornMorjLabel = new javax.swing.JLabel();
        FornMorjTextField = new javax.swing.JTextField();
        CPFCNPJjLabel = new javax.swing.JLabel();
        CPFCNPJjTextField = new javax.swing.JTextField();
        DtEmissaojLabel = new javax.swing.JLabel();
        DtEmissaojTextField = new javax.swing.JTextField();
        DtVencimentojLabel = new javax.swing.JLabel();
        DtVencimentojTextField = new javax.swing.JTextField();
        NroDocjLabel = new javax.swing.JLabel();
        NroDocjTextField = new javax.swing.JTextField();
        RecDesjLabel = new javax.swing.JLabel();
        RecDesjComboBox = new javax.swing.JComboBox<>();
        TipoPgtojLabel = new javax.swing.JLabel();
        TipoPgtojComboBox = new javax.swing.JComboBox<>();
        TipoLancjLabel = new javax.swing.JLabel();
        TipoLancjComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        FornMorjLabel.setText("Fornecedor/Morador:");

        CPFCNPJjLabel.setText("CPF/CNPJ:");

        DtEmissaojLabel.setText("Data emissão:");

        DtVencimentojLabel.setText("Data vencimento:");

        NroDocjLabel.setText("Nro. Documento:");

        RecDesjLabel.setText("Receita/Despesa:");

        RecDesjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RecDesjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecDesjComboBoxActionPerformed(evt);
            }
        });

        TipoPgtojLabel.setText("Tipo Pagamento:");

        TipoPgtojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoPgtojComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPgtojComboBoxActionPerformed(evt);
            }
        });

        TipoLancjLabel.setText("Tipo de Lançamento:");

        TipoLancjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoLancjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoLancjComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FornMorjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FornMorjTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DtEmissaojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DtEmissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DtVencimentojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DtVencimentojTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CPFCNPJjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPFCNPJjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroDocjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroDocjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoPgtojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoPgtojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RecDesjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecDesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoLancjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoLancjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecDesjLabel)
                    .addComponent(RecDesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FornMorjLabel)
                    .addComponent(FornMorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFCNPJjLabel)
                    .addComponent(CPFCNPJjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NroDocjLabel)
                    .addComponent(NroDocjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DtEmissaojLabel)
                    .addComponent(DtEmissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DtVencimentojLabel)
                    .addComponent(DtVencimentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoPgtojLabel)
                    .addComponent(TipoPgtojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoLancjLabel)
                    .addComponent(TipoLancjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RecDesjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecDesjComboBoxActionPerformed
        
    }//GEN-LAST:event_RecDesjComboBoxActionPerformed

    private void TipoPgtojComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPgtojComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPgtojComboBoxActionPerformed

    private void TipoLancjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoLancjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoLancjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFCNPJjLabel;
    private javax.swing.JTextField CPFCNPJjTextField;
    private javax.swing.JLabel DtEmissaojLabel;
    private javax.swing.JTextField DtEmissaojTextField;
    private javax.swing.JLabel DtVencimentojLabel;
    private javax.swing.JTextField DtVencimentojTextField;
    private javax.swing.JLabel FornMorjLabel;
    private javax.swing.JTextField FornMorjTextField;
    private javax.swing.JLabel NroDocjLabel;
    private javax.swing.JTextField NroDocjTextField;
    private javax.swing.JComboBox<String> RecDesjComboBox;
    private javax.swing.JLabel RecDesjLabel;
    private javax.swing.JComboBox<String> TipoLancjComboBox;
    private javax.swing.JLabel TipoLancjLabel;
    private javax.swing.JComboBox<String> TipoPgtojComboBox;
    private javax.swing.JLabel TipoPgtojLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
